- Cargo.toml
- src/fmt.rs
- tests/display.rs
- tests/fixtures/snapshots/stupicat-table-output
- tests/fixtures/table.md
- tests/fmt.rs
This builds on @euclio's work in https://github.com/Byron/pulldown-cmark-to-cmark/pull/2 and I think gets all the tests passing 🤞 
I had to change the fixtures and the snapshots though, see the commit messages for details.
@ehuss this is probably relevant to your interests too :)
> Pulldown cmark 0.4

- Cargo.toml
- src/fmt.rs
- tests/display.rs
- tests/fixtures/snapshots/stupicat-ordered-output
- tests/fixtures/snapshots/stupicat-output
- tests/fixtures/snapshots/stupicat-table-output
- tests/fixtures/snapshots/stupicat-unordered-output
- tests/fmt.rs
This is my initial attempt at fixing #6 . It makes some changes in the way we serialize blockquotes, so I opted to do most of my testing by verifying that the pulldown-cmark events line up before and after serializing.
Example differences 
```
> blockquote
```
is now serialized as
```
> 
> blockquote
```
this makes it easier to cover the edge case of an empty blockquote, without needing to preserve blockquote state across the events.
> Better support for blockquotes (#6)

- src/fmt.rs
- tests/cat.sh
- tests/fixtures/nested.md
- tests/fixtures/snapshots/stupicat-nested-output
- tests/fixtures/snapshots/stupicat-output
- tests/fmt.rs
Markdown allows for HTML elements, into which further markdown formatting is nested.
However only if the HTML element is spaced by an additional newline.
Relevant spec: https://spec.commonmark.org/0.28/#html-blocks
Fixes #10
---
So I came up with this solution, which is everything but pretty.
The only way I could make it work is by keeping state if we've seen an HTML element and are followed by a markdown element next.
This might actually add unecessary newlines, but _I think_ it should produce HTML that renders the same. I might be wrong and in certain circumstances that newline might cause different rendering though.
To make it short: it fixes my specific problem, but might cause others.
> Add newlines after HTML elemets if followed by more markdown

- src/lib.rs
- tests/cat.sh
- tests/display.rs
- tests/fixtures/lists-nested.md
- tests/fixtures/snapshots/stupicat-lists-nested-output
- tests/fmt.rs
Fixes #12
At least the prepending of newline.
The trailing ~~one~~ two newlines of a code block are at least configurable, so I can fix that in my usage. 
That means it's still not a _proper_ roundtrip from markdown to markdown, but fixing that is probably a bit more involved and requires touching a couple more tests.
> Add a newline before code blocks if necessary

- src/lib.rs
- tests/fixtures/snapshots/stupicat-table-output
- tests/fixtures/table.md
On some of our markdown we faced the following panic:
```
thread 'main' panicked at 'attempt to subtract with overflow', pulldown-cmark-to-cmark/src/lib.rs:382:50
```
It contained inline code in a table header, which the parser failed to collect and thus leading to a subtraction underflow when calculating the table header.
This is fixed in the first commit.
As a defensive mechanism I also swapped it to just saturate at 0.
This should still produce valid markdown tables, just won't be perfectly nice formatted (but then again they already miss accounting for emphasis (`_`) or strong formatting, so it's off-by-2 in those cases)
> Include code in table header

- src/lib.rs
This is a breaking change because it adds a member to the publicly
constructable `Options` struct.
Fixes https://github.com/Byron/pulldown-cmark-to-cmark/issues/17
> Make the number of backticks in codeblocks configurable

- tests/spec.rs
- tests/spec/CommonMark/LICENSE
- tests/spec/CommonMark/README.google
- tests/spec/CommonMark/smart_punct.txt
- tests/spec/CommonMark/spec.txt
This test parses the examples from CommonMark spec, regenerate markdown text using this crate and reparse the markdown text.
The expectation is that the two event lists are exactly the same.
The results currently on my machine is 389 passes out of 649 test cases.
> [POC] Add a test that verify current implementation against CommonMark spec

- src/lib.rs
- tests/cat.sh
- tests/fixtures/snapshots/stupicat-table-with-html-output
- tests/fixtures/table-with-html.md
- tests/fmt.rs
This was reported initially here: https://github.com/badboy/mdbook-toc/issues/19
> Don't add a newline after an HTML block if we're just ending another tag

- src/lib.rs
Link destinations containing spaces need to be formatted like `[link](<containing spaces>)`.
This brings the number of passing CommonMark test cases from 387 to 388.
> Handle spaces in link URIs

- src/lib.rs
- tests/fmt.rs
> Don't output extra newlines after HTML before a SoftBreak

- Cargo.toml
- src/lib.rs
- tests/fixtures/common-mark.md
- tests/fixtures/snapshots/stupicat-output
- tests/fmt.rs
This PR make library to retain autolink/email link format respecting author's choices.
Thank you, regards
see Byron/pulldown-cmark-to-cmark#23
> retain autolink/email link format

- Cargo.toml
- src/lib.rs
- tests/fixtures/common-mark.md
- tests/fixtures/snapshots/stupicat-output
- tests/fmt.rs
Hi! This PR implement an unopinionated management for `Linktype::Shortcut`s type links as identified by pulldown-cmark. Resulting output preserve the author's choice of putting a link in a file footer rather than inlining it.
I'm not totally convinced about `clone()`ing/reallocating stuff in required support data structures but being a rust newbie I'm currently unable to provide a better solution, given that there is any.
Hope this helps, thank you
see Byron/pulldown-cmark-to-cmark#32
> shortcut links implementation

- examples/stupicat.rs
- src/lib.rs
- tests/display.rs
- tests/fixtures/common-mark.md
- tests/fixtures/snapshots/stupicat-event-by-event-output
- tests/fixtures/snapshots/stupicat-output
- tests/fmt.rs
- tests/spec.rs
Hi, this is a tentative fix for #40. I've introduced some logic if we're working w/ state, and also had to move links' url inline otherwise they were broken if not at the end of line (see [tests](https://github.com/Byron/pulldown-cmark-to-cmark/compare/main...aogier:bugfix/40-shortcut_code?expand=1#diff-8ae4f4b9fc95a4103fc365a0a8631e4c9917171882848c967e23e61f900ff212R23)), let me know on that, maybe it could be made better in a next iteration on that.
Thank you, regards
Fixes #40
> properly render shortcut links w/ code formatting

- src/lib.rs
Looks like there was a little confusion when the previous updates were done, as the comments refer to a `cmark_with_options()` function that didn't exist.
> Add cmark_with_options() and fix comments

- src/lib.rs
- tests/cat.sh
- tests/fixtures/indented-code-block.md
- tests/fixtures/snapshots/stupicat-indented-code-block
- tests/fmt.rs
This PR also introduces a new public field `State::last_was_text_without_trailing_newline`.
fixes #48
> Inserts a newline if there is no newline before code block termination fence

- src/lib.rs
Currently, [rustdoc for `cmark_resume_with_options`](https://docs.rs/pulldown-cmark-to-cmark/10.0.4/pulldown_cmark_to_cmark/fn.cmark_resume_with_options.html) is a bit broken due to a wrongly indented nested list in a doc comment.
This PR fixes that issue.
Many thanks!
> Fix broken rustdoc due to a wrong indentation for a nested list in a doc comment

- src/lib.rs
- tests/fmt.rs
This PR adds `ordered_list_token` and `increment_ordered_list_bullets` fields to the `Options` struct to allow users to control the ordered list marker they want to use (`.` or `)`) and allows users to specify if they want to increment the ordered list number.
For example, setting `ordered_list_token=')'` and `increment_ordered_list_bullets=true` will format the following:
```markdown
1. one
1. two
1. three
```
as:
```markdown
1) one
2) two
3) three
```
> Add options for ordered list formatting

- src/lib.rs
- tests/fmt.rs
Before, `options.code_block_token` was used for inline code spans. Now we always use a backtick.
As far as I can tell from the [reference][1] and from [experimentation][2], code spans should always use one or more backticks and never use something else such as tildes.
The PR also ensures that we insert the necessary number of backticks to quote any backticks found in the code span itself. Before, only the case with a single backtick was handled, now the code can contain arbitrarily many backticks.
This was found using a fuzz test like the one in #55. The difference is that I restricted the input to a single paragraph of Markdown text, meaning that it only fuzzes inputs which match
[Event::Start(Tag::Paragraph), .., Event::End(Tag::Paragraph)]
There seems to be some more corner cases that …
> Handle inline code spans with multiple backticks

- LICENSE-APACHE
Adds a canned APACHE 2 license text for https://github.com/Byron/pulldown-cmark-to-cmark/issues/57.
For attribution, listed the authors as listed in the Cargo.toml file and picked 2018 as the year of the first commit to this github repository.
> add license texts

- src/lib.rs
- tests/fmt.rs
Currently, multiline footnotes are written out without indentation, which results in only the first line being interpreted as part of the footnote. This fixes that by writing four spaces before each subsequent line of a multiline footnote.
Also, according to [pandoc](https://pandoc.org/MANUAL.html#footnotes) and it seems `pulldown_cmark`, footnotes need to be separated by blank lines from other content, so I updated the existing test accordingly.
> Fix multiline footnotes

- src/lib.rs
- tests/fmt.rs
Currently, link titles are written without any escaping:
https://github.com/Byron/pulldown-cmark-to-cmark/blob/b1f77e0526b59a04234c0874cf00493720da550a/src/lib.rs#L591
This breaks links if the title contains interior quotes (see included test).
Since we always write link titles surrounded by double quotes, we should escape any interior double quotes that aren't already escaped.
See also https://spec.commonmark.org/0.30/#link-title
> Escape double quotes in link titles

- src/lib.rs
This PR adds `check_code_block_token_count` function which can be used to decide an appropriate valud of `code_block_token_count`.
See #20
> Add check_code_block_token_count function

- src/lib.rs
- tests/integrate.rs
This PR changes the return type of `count_code_block_tokens`.
By this change, the function can show "user can specify an arbitrary `code_block_token_count`" through `None` return value.
Refer: #20
> Change the return type of count_code_block_tokens

- Cargo.toml
- examples/stupicat.rs
- src/lib.rs
- tests/display.rs
- tests/fixtures/heading-id-classes.md
- tests/fixtures/snapshots/stupicat-event-by-event-output
- tests/fixtures/snapshots/stupicat-heading-id-classes-output
- tests/fixtures/snapshots/stupicat-nested-output
- tests/fixtures/snapshots/stupicat-output
- tests/fmt.rs
- tests/integrate.rs
- tests/spec.rs
[Version 0.10 of `pulldown-cmark` was just released with a number of breaking changes](https://github.com/pulldown-cmark/pulldown-cmark/releases/tag/v0.10.0). Unfortunately, it doesn't seem straightforward to update `pulldown-cmark-to-cmark`'s dependency on it. This is a start, but there are some breaking changes that will have to be worked around (compilation currently errors)
> Update `pulldown-cmark` dependency to 0.10

- src/lib.rs
- tests/cat.sh
- tests/fixtures/snapshots/stupicat-toml-frontmatter-output
- tests/fixtures/snapshots/stupicat-yaml-frontmatter-output
- tests/fixtures/toml-frontmatter.md
- tests/fixtures/yaml-frontmatter.md
- tests/fmt.rs
I have changed the yaml frontmatter endtag from `...` to `---` and added a `newlines_after_metadata` option.
Both frontmatter endtags were also missing a `\n` which I have added.
`newlines_after_metadata` defaults to `1` because it is the value used by prettier.
> fix: use correct yaml frontmatter end tag

- src/source_range.rs
- tests/fmt.rs
Fix #73.
The place that I messed up was that the `state.is_in_code_block` hack, especially the restoration was overriding `state` changes in `cmark_resume_one_event`, which is responsible for altering `state.is_in_code_block` based on whether we are entering a code block.
> fix(#73) do not disturb code block detection when preventing escape

- Cargo.toml
- src/lib.rs
- tests/cat.sh
- tests/display.rs
- tests/fixtures/common-mark.md
- tests/fixtures/math.md
- tests/fixtures/snapshots/stupicat-event-by-event-output
- tests/fixtures/snapshots/stupicat-math-output
- tests/fixtures/snapshots/stupicat-output
- tests/fmt.rs
Hi and thanks for this crate, it's super useful :)
I've started updating locally to `pulldown-cmark` `0.11.0` but not completely sure how to address the new `BlockQuoteKind`, `InlineMath` and `DisplayMath` properly so I thought I might as well open a PR.
> Update pulldown cmark

- src/lib.rs
- tests/fmt.rs
Emitting `::` in a table to indicate alignment is `Center` seems to break some parsers (at least `mdbook`'s). Emitting `:-:` appears to work fine.
This commit also removes an allocation when encountering an empty header cell. Rather than allocating a non-empty string, let the string be empty and add a minimum width for emitting alignments.
Also, I replaced what I think is a mismatch between characters and bytes in:
```rs
let last_minus_one = name.chars().count().saturating_sub(1);
for c in 0..name.len() {
```
`last_minus_one` counts in `char`s, while `c` counts in bytes.
This might fix #70.
> Fix emitting `::` for centered column in table.

- .github/workflows/rust.yml
- Cargo.toml
Adds an MSRV check to CI.
Checking the MSRV ensures that the minimum compiler version for this project is not inadvertently (/unintentionally) bumped by changes to dependencies or syntax.
I found the MSRV using cargo-msrv. Using cargo-no-dev-deps ensures that the dev dependencies don't contribute to the MSRV
> add MSRV check to CI

- .github/workflows/rust.yml
- Cargo.toml
- README.md
This project builds successfully with the MSRV of `pulldown-cmark`. Therefore we can lower `rust-version` to 1.71.1.
Add documentation for the current MSRV and that this project follows MSRV policy of `pulldown-cmark`.
Use `cargo hack` for MSRV CI job, to automatically install rustc according to `rust-version` and then execute `cargo check`.
> build: Lower MSRV to 1.71.1

- .github/workflows/rust.yml
- src/lib.rs
- src/source_range.rs
- tests/display.rs
- tests/fixtures/snapshots/stupicat-indented-code-block
- tests/fixtures/snapshots/stupicat-lists-nested-output
- tests/fmt.rs
This raises the number of passing spec tests from 459 to 473.
Fixes #69
> feat!: improve code block round-tripping

- src/lib.rs
- src/source_range.rs
- src/text_modifications.rs
- tests/display.rs
- tests/fmt.rs
- tests/source_range_fmt.rs
- tests/spec.rs
Raises spec tests from 578 to 580. It handles cases that look like these
Link, not image: \![a](b)
This header ends with hashes, not an ATX trailer ###
====================================================
| a \| b | a \| c |
|--------|--------|
> Drasticly improve escaping `!`, `#`, and `|`

- src/lib.rs
- src/source_range.rs
- src/text_modifications.rs
- tests/integrate/main.rs
This implements what I outlined in [this comment](https://github.com/Byron/pulldown-cmark-to-cmark/issues/91#issuecomment-2543059387).
One thought/remark I have is that I would have liked to add some information to the `UnexpectedEvent` variant, in particular:
```rs
pub enum CmarkError<'a> {
FormatFailed(fmt::Error),
UnexpectedEvent(Event<'a>),
}
```
I could make this work, but then I realized that it would most certainly break all consumers of this library, even those that treat the error as a `Box<dyn std::error::Error>`. This is because, if the `Event`s are local to the function that calls `cmark()`, that function cannot simply propagate the error to the caller (e.g. via `?`), since then it would outlive the events. The "stupicat" example would also fail to build for this exact reason. …
> Alternative approach for #91 with custom error type

- src/lib.rs
- src/text_modifications.rs
Hey 👋, big fan and first-time contributor to this project🙂
I'm building a Markdown editor that incorporates `pulldown-cmark-to-cmark`, and thought it might be time that I try to contribute some effort back to this project (and perhaps improve on a few issues I've run into). I've found that a great way to learn a new codebase is to start with making some small improvements that don't try to change behavior, so that's what I'm starting with here 🙂
Please let me know if you'd like anything changed with this patch, or if you'd prefer I start with some other kind of change.
<details>
<summary>
If you happen to be interested in how I'm putting this project to use, click here to read a bit about that.
</summary>
<br/>
I use `pulldown-cmark-to-cmark` as part of …
> refactor: Add helper to factor out newline + padding pattern

- src/lib.rs
- src/text_modifications.rs
This is a follow-up to #98, that uses the `write_padded_string()` helper in a handful of places I missed in that PR. 
Additionally, while in the neighhborhood, add `pub(crate)` to the other text_modifications.rs private helpers,
as [we discussed yesterday](https://github.com/Byron/pulldown-cmark-to-cmark/pull/98#discussion_r1959149931) 🙂. These being marked as `pub` is misleading since the `text_modifications` module is
not actually externally public, and these functions are never re-exported publicly.
---
Because you said:
> Thanks for offering. If you happen to keep contributing something else you could U-Boot that, but no need for a PR just for that.
I tucked the `pub(crate)` change into this PR instead of making a dedicated PR just for that small change. I am hoping to keep …
> refactor: Use `write_padded_string()` in a couple additional places (Part 2/X)

- src/lib.rs
Stacked PRs:
---
This should help with readability. As an example, I didn't realize
initially that all of the `if` statements updated in this PR
were actually modifying the same field.
But once I started doing the more generic refactoring of adding
a `set_option_minimum()` method, I looked at every line and
realized they were all the same.
Factoring this to a method should clarify to future readers that
updating newlines_before_start specifically is a recurring operation.
> refactor: Add `State::set_minimum_newlines_before_start()` (Part 3/X)    

- src/lib.rs
- src/text_modifications.rs
Stacked PRs:
----
My impression reading through the code in this project is that top-level statements have gotten a bit intertangled over time; this tries to reorder things to have a clearer flow and structure, grouping related things together.
For example, this moves the recently added Error enum up above all of the API functions, instead of leaving it somewhat arbitrarily nestled between `cmark_resume_with_options()` and `cmark_resume_one_event()`.
No code changes were made to the body of functions or types. This also does not change any of the public APIs, only where code is located.
* Group padded newline logic at top of text_modifications.rs
* Rename `padding_of()` to `list_item_padding_of()`
* Add 'Public API Functions' header in lib.rs
* Consolidate public enum and struct types at …
> refactor: Move and group related code (Part 4/X)

- src/lib.rs
- src/text_modifications.rs
Stacked PRs:
*Note: The diff for this PR will include all unmerged prior PRs, making it artificially large until rebased onto main.*
---
This is a small one, but hopefully improves readability a bit, and helps avoid string allocations.
> refactor: Add `Repeated` utility to simplify writing repeated content (Part 5/X)
